### ISSUE TITLE
Baseline Project Requirements

### ISSUE THREAD

**Issue by chris-cornish** [chris-cornish/fitness-frog#4]
# Fitness App

## Workout Log
- Workout DateTime
- Add exercise
 - New exercise
   - Exercise ID
    - Exercise name
    - Sets
    - Reps
    - Weight
    - Notes
 - Previously created exercise
- Edit
- Delete

## Food Log
- DateTime
- Calc to determine recommended intake of protein/fat/carbs/calories
 - cutting/maintaining/bulking
  - BMR
    - age
    - weight
    - sex
    - height
   - activity level
- Add food
  - New food
   - Food ID
   - Food Name
   - Fats
   - Carbs
   - Proteins
   - Calories
  - Previously created food
- Edit
- Delete
- Daily total
  - Fats
  - Carbs
  - Proteins
  - Calories

## Notes/Log/Picture
- DateTime
- Notes from workout
- Notes from food
- Add picture (for daily progress)
- Add note
- Edit
- Delete

## Personal/User Overview
- Age
- Sex
- Weight
- BMR
 - Determine BMR (calc)
- BMI
 - Determine BMI (calc)
- Body Fat
- Picture
- Calendar widget

**Comment by sclayturner** [comment]
Perfect.  This is what we needed.

**Comment by sclayturner** [comment]
@chris-cornish you can pull down the latest for this project. Reference the README file on the home page of the code. You may have some additional installation requirements (in readme).  We are going to go with the absolute bleeding-edge of Microsoft technology here because it's the go-forward pattern so best to learn it this way. This is why you had some trouble pulling down the Nuget template I specified originally...  This will follow more the Contosos University template, but starting with a clean slate and a mature way of laying out the solution for FitnessFrog.  Because this stuff is not totally mature even in the Microsoft world right now, getting the solution setup was a bit of a hodgepodge of tasks, but it should be pretty straight forward when you pull down the repository.
